### ISSUE TITLE
ur_rtde v1.6.0 fails to build with Boost 1.88.0

### ISSUE THREAD

**Issue by nmarks99** [nmarks99/URViewer#1]
**Problem:**

The `ur_rtde` library, when fetched using `FetchContent` at tag `v1.6.0`, fails to compile against newer versions of the Boost library.

**Error Message:**

When compiling with Boost 1.88.0, the build fails with the following error:

```
/home/nick/devel/URViewer/build/_deps/ur_rtde-src/include/ur_rtde/rtde.h:7:10: fatal error: boost/asio/io_service.hpp: No such file or directory
    7 | #include <boost/asio/io_service.hpp>
```

**Working Environment:**

*   **OS:** RHEL 9
*   **Boost Version:** `1.75.0`
*   **`ur_rtde` Version:** `v1.6.0` (via CMake `FetchContent`)
*   **Result:** Builds successfully.

**Failing Environment:**

*   **OS:** Arch Linux
*   **Boost Version:** `1.88.0`
*   **`ur_rtde` Version:** `v1.6.0` (via CMake `FetchContent`)
*   **Result:** Build fails.

**Cause:**

The `ur_rtde` `v1.6.0` tag includes `<boost/asio/io_service.hpp>`, which was deprecated in favor of `<boost/asio/io_context.hpp>` and has been removed in recent Boost versions like 1.88.0.

**Workaround:**

On the Arch Linux system, changing the `FetchContent` `GIT_TAG` for `ur_rtde` from `v1.6.0` to `master` allows the project to build successfully
